### ISSUE TITLE
Binary timer bug

### ISSUE THREAD

**Issue by Bobert-Brockson** [GamesDoneQuick/sgdq17-layouts#9]
The background to the timer is counting in pseudobinary, it isn't a true binary timer. Instead it is a binary representation of the associated digit. 

Normally it should count like this: 
```
             Any column
          Time increases ->                                       
|| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 ||
|| 0 | 0 | 0 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 0 ||
|| 0 | 1 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 0 ||
|| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 ||


```

Instead it counts like this in columns 0, 1, 3, 4, and 5. Where 0 is the right most column:

```
             Columns 0, 1, 3, 4, 5
          Time increases ->                                        
|| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 0 ||
|| 0 | 0 | 0 | 1 | 1 | 1 | 1 | 0 | 0 | 0 ||
|| 0 | 1 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 ||
|| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 ||


```

And like this in column 2:

```
             Column 2
          Time increases ->                                      
|| 0 | 0 | 0 | 0 | 0 | 0 ||
|| 0 | 0 | 0 | 1 | 1 | 0 ||
|| 0 | 1 | 1 | 0 | 0 | 0 ||
|| 1 | 0 | 1 | 0 | 1 | 0 ||


```

I mean I get that this cleanly converts it to base 10 or 6, but is isn't true binary timer anymore. Is this a decision, or would you like a pull request to address it?

**Comment by Lange** [comment]
Hi @imizaac,

Thanks for the attention to detail! The current behavior is indeed an intentional design choice.

As for pull requests, this is the repository for **S**GDQ 2017, and not AGDQ 2018. SGDQ 2017 did not have a binary representation of the timer, so there would be nothing for you to submit a pull request for.

Each event's grahpics are open sourced **after** the event has concluded. You can expect us to release `adgq18-layouts` sometime in early February.

Thanks again,
Alex
